name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --all --verbose
      - name: Test
        run: |
          cargo install cargo-nextest
          cargo nextest run
          cargo test --doc
      - name: Clippy
        run: cargo clippy --all -- -D warnings
      - name: Fmt
        run: cargo fmt --all -- --check
